# Generated by Django 5.1.7 on 2025-03-13 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
