# Generated by Django 5.0.4 on 2025-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprojects"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="userprojects",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprojects",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
