# Generated by Django 5.0.4 on 2025-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_name_alter_userprojects_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gitlab_url",
            field=models.URLField(blank=True, verbose_name="GitLab URL"),
        ),
    ]
