# Generated by Django 5.0.4 on 2025-03-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_gitlab_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprojects",
            old_name="repository_url",
            new_name="link",
        ),
        migrations.AlterField(
            model_name="userprojects",
            name="forks",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userprojects",
            name="stars",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
