# Generated by Django 5.0.4 on 2025-03-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_repository_url_userprojects_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprojects",
            old_name="name",
            new_name="project_name",
        ),
    ]
