# Generated by Django 5.0.4 on 2025-03-13 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="updated at"
            ),
        ),
    ]
